cargo-features = ["edition"]

[package]
authors = ["John Hodge <tpg@mutabah.net>"]
name = "equation"
version = "0.1.0"

edition = "2018"

[dependencies]
iui = "0.3"
pancurses = "0.16"
plex = "0.2.3"
structopt = "0.2"
